// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RET int32

const (
	RET_RET_ERROR           RET = 0 //错误 提示文字：错误
	RET_RET_OK              RET = 1 //OK 提示文字：成功
	RET_RET_SERVER_MAINTAIN RET = 2 //服务器没有开启(服务器进程没有开启) 提示文字：服务器暂未开放
)

// Enum value maps for RET.
var (
	RET_name = map[int32]string{
		0: "RET_ERROR",
		1: "RET_OK",
		2: "RET_SERVER_MAINTAIN",
	}
	RET_value = map[string]int32{
		"RET_ERROR":           0,
		"RET_OK":              1,
		"RET_SERVER_MAINTAIN": 2,
	}
)

func (x RET) Enum() *RET {
	p := new(RET)
	*p = x
	return p
}

func (x RET) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RET) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (RET) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x RET) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RET.Descriptor instead.
func (RET) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type ID int32

const (
	ID_MSG_NONE          ID = 0
	ID_MSG_LOGIC_MIN     ID = 10000
	ID_MSG_LOGIC_MAX     ID = 30000
	ID_MSG_BEGIN         ID = 10001
	ID_MSG_END           ID = 10999
	ID_MSG_C2G_Login     ID = 10002
	ID_MSG_G2C_Login     ID = 10003
	ID_MSG_C2G_Create    ID = 10004
	ID_MSG_G2C_Create    ID = 10005
	ID_MSG_C2G_Offline   ID = 10006
	ID_MSG_C2G_KeepAlive ID = 10007 // Client->Gateway保持连接
	ID_MSG_G2C_KeepAlive ID = 10008 // Logic->Gateway保持连接
	ID_MSG_C2G_SayHi     ID = 10009 // Gateway->Logic 告诉Logic自己的GatewayID
	ID_MSG_G2C_SayHi     ID = 10010 // Logic->Gateway 向Gateway返回Logic注册服务器ID(可多个)
	ID_MSG_G2C_Broadcast ID = 10011
	ID_MSG_G2C_Offline   ID = 10012
)

// Enum value maps for ID.
var (
	ID_name = map[int32]string{
		0:     "MSG_NONE",
		10000: "MSG_LOGIC_MIN",
		30000: "MSG_LOGIC_MAX",
		10001: "MSG_BEGIN",
		10999: "MSG_END",
		10002: "MSG_C2G_Login",
		10003: "MSG_G2C_Login",
		10004: "MSG_C2G_Create",
		10005: "MSG_G2C_Create",
		10006: "MSG_C2G_Offline",
		10007: "MSG_C2G_KeepAlive",
		10008: "MSG_G2C_KeepAlive",
		10009: "MSG_C2G_SayHi",
		10010: "MSG_G2C_SayHi",
		10011: "MSG_G2C_Broadcast",
		10012: "MSG_G2C_Offline",
	}
	ID_value = map[string]int32{
		"MSG_NONE":          0,
		"MSG_LOGIC_MIN":     10000,
		"MSG_LOGIC_MAX":     30000,
		"MSG_BEGIN":         10001,
		"MSG_END":           10999,
		"MSG_C2G_Login":     10002,
		"MSG_G2C_Login":     10003,
		"MSG_C2G_Create":    10004,
		"MSG_G2C_Create":    10005,
		"MSG_C2G_Offline":   10006,
		"MSG_C2G_KeepAlive": 10007,
		"MSG_G2C_KeepAlive": 10008,
		"MSG_C2G_SayHi":     10009,
		"MSG_G2C_SayHi":     10010,
		"MSG_G2C_Broadcast": 10011,
		"MSG_G2C_Offline":   10012,
	}
)

func (x ID) Enum() *ID {
	p := new(ID)
	*p = x
	return p
}

func (x ID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ID) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (ID) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x ID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ID.Descriptor instead.
func (ID) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

// 客户端登陆消息
type C2G_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId uint64 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"` // 服务器id
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                          // data
}

func (x *C2G_Login) Reset() {
	*x = C2G_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2G_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2G_Login) ProtoMessage() {}

func (x *C2G_Login) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2G_Login.ProtoReflect.Descriptor instead.
func (*C2G_Login) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *C2G_Login) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *C2G_Login) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 返回客户端登陆消息
type G2C_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret  RET    `protobuf:"varint,1,opt,name=ret,proto3,enum=message.RET" json:"ret,omitempty"` // 返回码
	Uid  uint64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                  // 玩家id
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                 // data
}

func (x *G2C_Login) Reset() {
	*x = G2C_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2C_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2C_Login) ProtoMessage() {}

func (x *G2C_Login) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2C_Login.ProtoReflect.Descriptor instead.
func (*G2C_Login) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *G2C_Login) GetRet() RET {
	if x != nil {
		return x.Ret
	}
	return RET_RET_ERROR
}

func (x *G2C_Login) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *G2C_Login) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 下线消息
type C2G_Offline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2G_Offline) Reset() {
	*x = C2G_Offline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2G_Offline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2G_Offline) ProtoMessage() {}

func (x *C2G_Offline) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2G_Offline.ProtoReflect.Descriptor instead.
func (*C2G_Offline) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

// gateway向server发送连接成功消息
type C2G_SayHi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2G_SayHi) Reset() {
	*x = C2G_SayHi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2G_SayHi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2G_SayHi) ProtoMessage() {}

func (x *C2G_SayHi) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2G_SayHi.ProtoReflect.Descriptor instead.
func (*C2G_SayHi) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

// server向gateway发送server的id信息
type G2C_SayHi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //current已经包含了这个id，在go的实现中不要这个了
	Current []uint64 `protobuf:"varint,2,rep,packed,name=current,proto3" json:"current,omitempty"`
	Del     []uint64 `protobuf:"varint,3,rep,packed,name=del,proto3" json:"del,omitempty"`
}

func (x *G2C_SayHi) Reset() {
	*x = G2C_SayHi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2C_SayHi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2C_SayHi) ProtoMessage() {}

func (x *G2C_SayHi) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2C_SayHi.ProtoReflect.Descriptor instead.
func (*G2C_SayHi) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *G2C_SayHi) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *G2C_SayHi) GetCurrent() []uint64 {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *G2C_SayHi) GetDel() []uint64 {
	if x != nil {
		return x.Del
	}
	return nil
}

// 客户端发送心跳消息
type C2G_KeepAlive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2G_KeepAlive) Reset() {
	*x = C2G_KeepAlive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2G_KeepAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2G_KeepAlive) ProtoMessage() {}

func (x *C2G_KeepAlive) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2G_KeepAlive.ProtoReflect.Descriptor instead.
func (*C2G_KeepAlive) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

// 返回客户端发送心跳消息
type G2C_KeepAlive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *G2C_KeepAlive) Reset() {
	*x = G2C_KeepAlive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2C_KeepAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2C_KeepAlive) ProtoMessage() {}

func (x *G2C_KeepAlive) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2C_KeepAlive.ProtoReflect.Descriptor instead.
func (*G2C_KeepAlive) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

//广播消息 ids是要广播的人的集合，如果集合为空表示向全部在线的人发送
type G2C_Broadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids  []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Cmd  uint32   `protobuf:"varint,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Data []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *G2C_Broadcast) Reset() {
	*x = G2C_Broadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2C_Broadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2C_Broadcast) ProtoMessage() {}

func (x *G2C_Broadcast) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2C_Broadcast.ProtoReflect.Descriptor instead.
func (*G2C_Broadcast) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *G2C_Broadcast) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *G2C_Broadcast) GetCmd() uint32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *G2C_Broadcast) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

//
type G2C_Offline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *G2C_Offline) Reset() {
	*x = G2C_Offline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *G2C_Offline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*G2C_Offline) ProtoMessage() {}

func (x *G2C_Offline) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use G2C_Offline.ProtoReflect.Descriptor instead.
func (*G2C_Offline) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

var File_message_proto protoreflect.FileDescriptor

var file_message_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3c, 0x0a, 0x09, 0x43, 0x32, 0x47, 0x5f,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x51, 0x0a, 0x09, 0x47, 0x32, 0x43, 0x5f, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x12, 0x1e, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0c, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x45, 0x54, 0x52, 0x03,
	0x72, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0d, 0x0a, 0x0b, 0x43, 0x32, 0x47,
	0x5f, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x0b, 0x0a, 0x09, 0x43, 0x32, 0x47, 0x5f,
	0x53, 0x61, 0x79, 0x48, 0x69, 0x22, 0x47, 0x0a, 0x09, 0x47, 0x32, 0x43, 0x5f, 0x53, 0x61, 0x79,
	0x48, 0x69, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x64, 0x65, 0x6c, 0x22, 0x0f,
	0x0a, 0x0d, 0x43, 0x32, 0x47, 0x5f, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x22,
	0x0f, 0x0a, 0x0d, 0x47, 0x32, 0x43, 0x5f, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65,
	0x22, 0x47, 0x0a, 0x0d, 0x47, 0x32, 0x43, 0x5f, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03,
	0x69, 0x64, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x32, 0x43,
	0x5f, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x2a, 0x39, 0x0a, 0x03, 0x52, 0x45, 0x54, 0x12,
	0x0d, 0x0a, 0x09, 0x52, 0x45, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x52, 0x45, 0x54, 0x5f, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45,
	0x54, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x4d, 0x41, 0x49, 0x4e, 0x54, 0x41, 0x49,
	0x4e, 0x10, 0x02, 0x2a, 0xc7, 0x02, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x53,
	0x47, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0d, 0x4d, 0x53, 0x47, 0x5f,
	0x4c, 0x4f, 0x47, 0x49, 0x43, 0x5f, 0x4d, 0x49, 0x4e, 0x10, 0x90, 0x4e, 0x12, 0x13, 0x0a, 0x0d,
	0x4d, 0x53, 0x47, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x43, 0x5f, 0x4d, 0x41, 0x58, 0x10, 0xb0, 0xea,
	0x01, 0x12, 0x0e, 0x0a, 0x09, 0x4d, 0x53, 0x47, 0x5f, 0x42, 0x45, 0x47, 0x49, 0x4e, 0x10, 0x91,
	0x4e, 0x12, 0x0c, 0x0a, 0x07, 0x4d, 0x53, 0x47, 0x5f, 0x45, 0x4e, 0x44, 0x10, 0xf7, 0x55, 0x12,
	0x12, 0x0a, 0x0d, 0x4d, 0x53, 0x47, 0x5f, 0x43, 0x32, 0x47, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x10, 0x92, 0x4e, 0x12, 0x12, 0x0a, 0x0d, 0x4d, 0x53, 0x47, 0x5f, 0x47, 0x32, 0x43, 0x5f, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x10, 0x93, 0x4e, 0x12, 0x13, 0x0a, 0x0e, 0x4d, 0x53, 0x47, 0x5f, 0x43,
	0x32, 0x47, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x10, 0x94, 0x4e, 0x12, 0x13, 0x0a, 0x0e,
	0x4d, 0x53, 0x47, 0x5f, 0x47, 0x32, 0x43, 0x5f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x10, 0x95,
	0x4e, 0x12, 0x14, 0x0a, 0x0f, 0x4d, 0x53, 0x47, 0x5f, 0x43, 0x32, 0x47, 0x5f, 0x4f, 0x66, 0x66,
	0x6c, 0x69, 0x6e, 0x65, 0x10, 0x96, 0x4e, 0x12, 0x16, 0x0a, 0x11, 0x4d, 0x53, 0x47, 0x5f, 0x43,
	0x32, 0x47, 0x5f, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x10, 0x97, 0x4e, 0x12,
	0x16, 0x0a, 0x11, 0x4d, 0x53, 0x47, 0x5f, 0x47, 0x32, 0x43, 0x5f, 0x4b, 0x65, 0x65, 0x70, 0x41,
	0x6c, 0x69, 0x76, 0x65, 0x10, 0x98, 0x4e, 0x12, 0x12, 0x0a, 0x0d, 0x4d, 0x53, 0x47, 0x5f, 0x43,
	0x32, 0x47, 0x5f, 0x53, 0x61, 0x79, 0x48, 0x69, 0x10, 0x99, 0x4e, 0x12, 0x12, 0x0a, 0x0d, 0x4d,
	0x53, 0x47, 0x5f, 0x47, 0x32, 0x43, 0x5f, 0x53, 0x61, 0x79, 0x48, 0x69, 0x10, 0x9a, 0x4e, 0x12,
	0x16, 0x0a, 0x11, 0x4d, 0x53, 0x47, 0x5f, 0x47, 0x32, 0x43, 0x5f, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x10, 0x9b, 0x4e, 0x12, 0x14, 0x0a, 0x0f, 0x4d, 0x53, 0x47, 0x5f, 0x47,
	0x32, 0x43, 0x5f, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x9c, 0x4e, 0x42, 0x0c, 0x5a,
	0x0a, 0x2e, 0x2f, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData = file_message_proto_rawDesc
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_proto_rawDescData)
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_message_proto_goTypes = []interface{}{
	(RET)(0),              // 0: message.RET
	(ID)(0),               // 1: message.ID
	(*C2G_Login)(nil),     // 2: message.C2G_Login
	(*G2C_Login)(nil),     // 3: message.G2C_Login
	(*C2G_Offline)(nil),   // 4: message.C2G_Offline
	(*C2G_SayHi)(nil),     // 5: message.C2G_SayHi
	(*G2C_SayHi)(nil),     // 6: message.G2C_SayHi
	(*C2G_KeepAlive)(nil), // 7: message.C2G_KeepAlive
	(*G2C_KeepAlive)(nil), // 8: message.G2C_KeepAlive
	(*G2C_Broadcast)(nil), // 9: message.G2C_Broadcast
	(*G2C_Offline)(nil),   // 10: message.G2C_Offline
}
var file_message_proto_depIdxs = []int32{
	0, // 0: message.G2C_Login.ret:type_name -> message.RET
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2G_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2C_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2G_Offline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2G_SayHi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2C_SayHi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2G_KeepAlive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2C_KeepAlive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2C_Broadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*G2C_Offline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_rawDesc = nil
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
